### ISSUE TITLE
Not getting an import

### ISSUE THREAD

**Issue by Superdominik** [joefitzgerald/go-get#23]
Hi, I just put

```
import (

  ...

  _ "github.com/lib/pq"

  ...

)
```

into my source code, but go-get doesn't get this package for me. All the other imports worked fine. I had to manually get it myself.

**Comment by joefitzgerald** [comment]
This is expected bahavior. The go-get package provides a keyboard shortcut and a command that you can use to go get a package; but many people don't use go get to fetch dependencies (e.g. Using glide instead); fetching new dependencies is an explicit action that you initiate.

**Comment by Superdominik** [comment]
I see. I didn't realize from the readme how it works exactly. That you'd invoke it only with a keybinding.

I expected a notification on the top right, with a button, that would let me click to go get. The same way it asked me to get the metalinter package when I first installed go-plus.

Thanks for clarifying.
