### ISSUE TITLE
go-get asks to update gocode, than fails

### ISSUE THREAD

**Issue by andradei** [joefitzgerald/go-get#27]
Fail message:

> package github.com/nsf/gocode: cannot download, $GOPATH not set. For more details see: go help gopath

GOPATH is set properly though, other text editors and IDEs I tried find it just fine.

**Comment by zmb3** [comment]
Are you running the latest version of Atom (1.9.8)?  There was an issue in previous versions that was just fixed.

**Comment by andradei** [comment]
I am using Atom 1.9.8.

**Comment by joefitzgerald** [comment]
The fix is not out yet; you need to keep an eye out for `1.9.9`. In the interim, you need to launch atom from your terminal.

**Comment by joefitzgerald** [comment]
https://github.com/atom/atom/pull/12396

**Comment by andradei** [comment]
@joefitzgerald Awesome thanks for fixing it over there.
