### ISSUE TITLE
Error Getting Package: Bad argument

### ISSUE THREAD

**Issue by pierrre** [joefitzgerald/go-get#3]
I have a window:

```
Would you like to run go get -ugolang.org/x/tools/cmd/goimports?

Run Go Get
```

I click `Run Go Get`.

It displays a message:

```
Error Getting Package
Bad argument
```

And there is another message in the dev console:

```
TypeError: Bad argument(…)         manager.js:85
```

Line 85 in manager.js is

``` js
console.log(r.error)
```

**Comment by joefitzgerald** [comment]
Can you reproduce this?

**Comment by pierrre** [comment]
Actually, it happens if the GOPATH is not detected.
I fixed this bug by starting Atom from the terminal.
