### ISSUE TITLE
Can we configure the path that go-get installs to?

### ISSUE THREAD

**Issue by elsigh** [joefitzgerald/go-get#4]
I'm not sure where to find it (I see there's another package called environment, but I don't see how to configure go-get directly?).. Sorry if this is the wrong project for this, but anyway, I want to tell go-get to install things into my build directory (it's installing them into my source tree presently).

**Comment by zmb3** [comment]
The `go-get` package just calls the Go tool's `go get` command, which clones the source code into `$GOPATH/src` and then compiles and installs to `$GOPATH/pkg` and `$GOPATH/bin`.

**Comment by elsigh** [comment]
Ah, ok looks like I need to override $GOPATH for the plugin inasmuch as my  first entry is not the one where I want it to install to, though it's the one where I first want other tools to look for installs.
I feel like GOPATH used to be a configuration option in Preferences in Atom, but I don't see it now.. Is there a way to override the env var?

**Comment by elsigh** [comment]
Looks like I can change config's goPath according to https://libraries.io/atom/go-plus
