### ISSUE TITLE
Go Get can't find $GOPATH from system environment

### ISSUE THREAD

**Issue by othpiik** [joefitzgerald/go-get#6]
> Go Get The gofmt package uses the goimports tool, but it cannot be found. 
> Would you like to run go get -u golang.org/x/tools/cmd/goimports?

when Go Get

```
Error Getting Package
# cd /home/oh/go/src/golang.org/x/tools; git pull --ff-only
error: Your local changes to the following files would be overwritten by merge:
    go/importer/import.go
Please, commit your changes or stash them before you can merge.
Aborting
Updating 5a2fc32..3b9441c
package golang.org/x/tools/cmd/goimports: exit status 1
```

Seem Go Get can't find $GOPATH from system environment

**Comment by joefitzgerald** [comment]
Your issue is you have modified a file in the tools repo. You need to either commit it, or revert it.
